export const KEYBOARD_SHORTCUTS: Record<string, string> = {
  'Delete / Backspace': 'Delete selected objects',
  'Ctrl + C': 'Copy',
  'Ctrl + V': 'Paste',
  'Ctrl + D': 'Duplicate',
  'Ctrl + Z': 'Undo',
  'Ctrl + Shift + Z': 'Redo',
  'Ctrl + A': 'Select all',
  'Ctrl + G': 'Group selected',
  'Ctrl + Shift + G': 'Ungroup',
  'Ctrl + [': 'Send backward',
  'Ctrl + ]': 'Bring forward',
  'Arrow Keys': 'Nudge (1px)',
  'Shift + Arrow Keys': 'Nudge (10px)',
  'Ctrl + +': 'Zoom in',
  'Ctrl + -': 'Zoom out',
  'Ctrl + 0': 'Reset zoom',
  'Escape': 'Deselect / Switch to select tool',
}
