import type { CanvasTemplate } from '@/types/project.types'

/**
 * Built-in templates — each contains a set of pre-built Fabric.js objects
 * that load onto the canvas when selected.
 */
export const TEMPLATES: CanvasTemplate[] = [
  // ─── Instagram Post ──────────────────────────────────────────────────────
  {
    id: 'instagram-post',
    name: 'Instagram Post',
    category: 'social',
    description: 'Bold social media post',
    thumbnail: '📸',
    width: 1080,
    height: 1080,
    backgroundColor: '#1a1a2e',
    objects: [
      {
        type: 'rect',
        left: 0, top: 0, width: 1080, height: 1080,
        fill: 'linear-gradient(135deg, #6366f1 0%, #8b5cf6 100%)',
        selectable: false, evented: false,
      },
      {
        type: 'textbox',
        text: 'YOUR BRAND',
        left: 80, top: 80, width: 600,
        fontSize: 48, fontWeight: '700', fontFamily: 'Inter',
        fill: 'rgba(255,255,255,0.9)',
        charSpacing: 200,
      },
      {
        type: 'textbox',
        text: 'AMAZING\nHEADLINE\nHERE',
        left: 80, top: 260, width: 900,
        fontSize: 120, fontWeight: '800', fontFamily: 'Inter',
        fill: '#ffffff', lineHeight: 0.9,
      },
      {
        type: 'rect',
        left: 80, top: 750, width: 200, height: 6,
        fill: '#ec4899', rx: 3, ry: 3,
      },
      {
        type: 'textbox',
        text: 'www.yourbrand.com',
        left: 80, top: 800, width: 600,
        fontSize: 28, fontFamily: 'Inter',
        fill: 'rgba(255,255,255,0.7)',
      },
    ],
  },

  // ─── Poster ──────────────────────────────────────────────────────────────
  {
    id: 'event-poster',
    name: 'Event Poster',
    category: 'poster',
    description: 'Vibrant event poster',
    thumbnail: '🎨',
    width: 2480,
    height: 3508,
    backgroundColor: '#0f0f13',
    objects: [
      {
        type: 'rect',
        left: 0, top: 0, width: 2480, height: 3508,
        fill: '#0f0f13', selectable: false, evented: false,
      },
      {
        type: 'circle',
        left: 1200, top: -200, radius: 900,
        fill: 'rgba(99,102,241,0.3)', selectable: false,
      },
      {
        type: 'textbox',
        text: 'GRAND\nEVENT\n2026',
        left: 120, top: 300, width: 2200,
        fontSize: 320, fontWeight: '900', fontFamily: 'Inter',
        fill: '#ffffff', textAlign: 'center', lineHeight: 0.85,
      },
      {
        type: 'rect',
        left: 800, top: 1700, width: 880, height: 8,
        fill: '#6366f1', rx: 4, ry: 4,
      },
      {
        type: 'textbox',
        text: 'SATURDAY — JULY 26, 2026',
        left: 120, top: 1780, width: 2200,
        fontSize: 64, fontWeight: '600', fontFamily: 'Inter',
        fill: '#a5b4fc', textAlign: 'center', charSpacing: 150,
      },
      {
        type: 'textbox',
        text: 'Main Arena, Downtown City',
        left: 120, top: 1900, width: 2200,
        fontSize: 52, fontFamily: 'Inter',
        fill: 'rgba(255,255,255,0.6)', textAlign: 'center',
      },
    ],
  },

  // ─── Flyer ───────────────────────────────────────────────────────────────
  {
    id: 'promo-flyer',
    name: 'Promo Flyer',
    category: 'flyer',
    description: 'Eye-catching promotional flyer',
    thumbnail: '📄',
    width: 816,
    height: 1056,
    backgroundColor: '#ffffff',
    objects: [
      {
        type: 'rect',
        left: 0, top: 0, width: 816, height: 400,
        fill: '#6366f1', selectable: false, evented: false,
      },
      {
        type: 'textbox',
        text: '50% OFF',
        left: 40, top: 80, width: 736,
        fontSize: 120, fontWeight: '900', fontFamily: 'Inter',
        fill: '#ffffff', textAlign: 'center',
      },
      {
        type: 'textbox',
        text: 'EVERYTHING SALE',
        left: 40, top: 260, width: 736,
        fontSize: 36, fontWeight: '700', fontFamily: 'Inter',
        fill: 'rgba(255,255,255,0.85)', textAlign: 'center',
        charSpacing: 200,
      },
      {
        type: 'textbox',
        text: 'Shop Now & Save Big',
        left: 40, top: 460, width: 736,
        fontSize: 48, fontWeight: '700', fontFamily: 'Inter',
        fill: '#1a1a2e', textAlign: 'center',
      },
      {
        type: 'textbox',
        text: 'Valid until July 31, 2026\nUse code: MINI50',
        left: 40, top: 560, width: 736,
        fontSize: 28, fontFamily: 'Inter',
        fill: '#64748b', textAlign: 'center', lineHeight: 1.6,
      },
      {
        type: 'rect',
        left: 208, top: 720, width: 400, height: 80,
        fill: '#6366f1', rx: 40, ry: 40,
      },
      {
        type: 'textbox',
        text: 'SHOP NOW',
        left: 208, top: 736, width: 400,
        fontSize: 32, fontWeight: '700', fontFamily: 'Inter',
        fill: '#ffffff', textAlign: 'center',
      },
    ],
  },

  // ─── Certificate ─────────────────────────────────────────────────────────
  {
    id: 'certificate',
    name: 'Certificate',
    category: 'certificate',
    description: 'Elegant certificate of completion',
    thumbnail: '🏆',
    width: 1080,
    height: 756,
    backgroundColor: '#faf7f0',
    objects: [
      {
        type: 'rect',
        left: 0, top: 0, width: 1080, height: 756,
        fill: '#faf7f0', selectable: false, evented: false,
      },
      {
        type: 'rect',
        left: 20, top: 20, width: 1040, height: 716,
        fill: 'transparent', stroke: '#c9a84c', strokeWidth: 4,
        rx: 4, ry: 4, selectable: false,
      },
      {
        type: 'rect',
        left: 30, top: 30, width: 1020, height: 696,
        fill: 'transparent', stroke: '#c9a84c', strokeWidth: 1,
        rx: 2, ry: 2, selectable: false,
      },
      {
        type: 'textbox',
        text: 'Certificate of Achievement',
        left: 40, top: 80, width: 1000,
        fontSize: 52, fontWeight: '700', fontFamily: 'Georgia',
        fill: '#1a1a2e', textAlign: 'center',
      },
      {
        type: 'rect',
        left: 440, top: 180, width: 200, height: 3,
        fill: '#c9a84c',
      },
      {
        type: 'textbox',
        text: 'This certifies that',
        left: 40, top: 220, width: 1000,
        fontSize: 24, fontFamily: 'Georgia',
        fill: '#64748b', textAlign: 'center', fontStyle: 'italic',
      },
      {
        type: 'textbox',
        text: 'Recipient Name',
        left: 40, top: 280, width: 1000,
        fontSize: 72, fontWeight: '700', fontFamily: 'Georgia',
        fill: '#6366f1', textAlign: 'center',
      },
      {
        type: 'textbox',
        text: 'has successfully completed the course',
        left: 40, top: 380, width: 1000,
        fontSize: 24, fontFamily: 'Georgia',
        fill: '#64748b', textAlign: 'center',
      },
      {
        type: 'textbox',
        text: 'Advanced Web Development',
        left: 40, top: 420, width: 1000,
        fontSize: 36, fontWeight: '700', fontFamily: 'Inter',
        fill: '#1a1a2e', textAlign: 'center',
      },
      {
        type: 'textbox',
        text: 'July 24, 2026',
        left: 150, top: 590, width: 300,
        fontSize: 22, fontFamily: 'Georgia',
        fill: '#1a1a2e', textAlign: 'center',
      },
      {
        type: 'rect',
        left: 150, top: 630, width: 300, height: 2,
        fill: '#1a1a2e',
      },
      {
        type: 'textbox',
        text: 'Date',
        left: 150, top: 640, width: 300,
        fontSize: 18, fontFamily: 'Inter',
        fill: '#64748b', textAlign: 'center',
      },
    ],
  },

  // ─── Resume ───────────────────────────────────────────────────────────────
  {
    id: 'resume',
    name: 'Resume Page',
    category: 'resume',
    description: 'Modern minimal resume',
    thumbnail: '📋',
    width: 816,
    height: 1056,
    backgroundColor: '#ffffff',
    objects: [
      {
        type: 'rect',
        left: 0, top: 0, width: 220, height: 1056,
        fill: '#1e1e2c', selectable: false, evented: false,
      },
      {
        type: 'circle',
        left: 60, top: 40, radius: 60,
        fill: '#6366f1',
      },
      {
        type: 'textbox',
        text: 'Your\nName',
        left: 8, top: 200, width: 204,
        fontSize: 32, fontWeight: '700', fontFamily: 'Inter',
        fill: '#ffffff', textAlign: 'center', lineHeight: 1.1,
      },
      {
        type: 'textbox',
        text: 'UX Designer',
        left: 8, top: 290, width: 204,
        fontSize: 18, fontFamily: 'Inter',
        fill: '#a5b4fc', textAlign: 'center',
      },
      {
        type: 'textbox',
        text: 'CONTACT',
        left: 16, top: 380, width: 188,
        fontSize: 14, fontWeight: '700', fontFamily: 'Inter',
        fill: '#a5b4fc', charSpacing: 200,
      },
      {
        type: 'textbox',
        text: 'email@example.com\n+1 234 567 890\ncity, Country',
        left: 16, top: 410, width: 188,
        fontSize: 13, fontFamily: 'Inter',
        fill: 'rgba(255,255,255,0.75)', lineHeight: 1.7,
      },
      {
        type: 'textbox',
        text: 'SKILLS',
        left: 16, top: 540, width: 188,
        fontSize: 14, fontWeight: '700', fontFamily: 'Inter',
        fill: '#a5b4fc', charSpacing: 200,
      },
      {
        type: 'textbox',
        text: 'Figma / Sketch\nHTML & CSS\nReact\nUser Research\nPrototyping',
        left: 16, top: 568, width: 188,
        fontSize: 13, fontFamily: 'Inter',
        fill: 'rgba(255,255,255,0.75)', lineHeight: 1.8,
      },
      // Right column
      {
        type: 'textbox',
        text: 'PROFESSIONAL SUMMARY',
        left: 248, top: 50, width: 540,
        fontSize: 14, fontWeight: '700', fontFamily: 'Inter',
        fill: '#6366f1', charSpacing: 200,
      },
      {
        type: 'rect',
        left: 248, top: 80, width: 540, height: 2,
        fill: '#e2e8f0',
      },
      {
        type: 'textbox',
        text: 'Creative and detail-oriented UX Designer with 5+ years of experience crafting user-centered digital experiences. Passionate about transforming complex problems into elegant solutions.',
        left: 248, top: 96, width: 540,
        fontSize: 14, fontFamily: 'Inter',
        fill: '#475569', lineHeight: 1.7,
      },
    ],
  },

  // ─── Business Card ────────────────────────────────────────────────────────
  {
    id: 'business-card',
    name: 'Business Card',
    category: 'business-card',
    description: 'Sleek dark business card',
    thumbnail: '💼',
    width: 1050,
    height: 600,
    backgroundColor: '#1e1e2c',
    objects: [
      {
        type: 'rect',
        left: 0, top: 0, width: 1050, height: 600,
        fill: '#1e1e2c', selectable: false, evented: false,
      },
      {
        type: 'rect',
        left: 0, top: 0, width: 8, height: 600,
        fill: '#6366f1', selectable: false,
      },
      {
        type: 'circle',
        left: 820, top: -100, radius: 350,
        fill: 'rgba(99,102,241,0.08)', selectable: false,
      },
      {
        type: 'textbox',
        text: 'Alex Johnson',
        left: 60, top: 80, width: 700,
        fontSize: 72, fontWeight: '700', fontFamily: 'Inter',
        fill: '#ffffff',
      },
      {
        type: 'textbox',
        text: 'Chief Design Officer',
        left: 60, top: 185, width: 500,
        fontSize: 28, fontFamily: 'Inter',
        fill: '#a5b4fc',
      },
      {
        type: 'rect',
        left: 60, top: 250, width: 200, height: 3,
        fill: '#6366f1', rx: 1.5, ry: 1.5,
      },
      {
        type: 'textbox',
        text: 'alex@company.com\n+1 (555) 000-1234\nwww.company.com',
        left: 60, top: 290, width: 500,
        fontSize: 22, fontFamily: 'Inter',
        fill: 'rgba(255,255,255,0.6)', lineHeight: 1.8,
      },
    ],
  },
  // ─── Twitter Header (social) ─────────────────────────────────────────────
  {
    id: 'twitter-header',
    name: 'Twitter Header',
    category: 'social',
    description: 'Sleek banner for Twitter profile',
    thumbnail: '🐦',
    width: 1500,
    height: 500,
    backgroundColor: '#0f172a',
    objects: [
      {
        type: 'rect',
        left: 0, top: 0, width: 1500, height: 500,
        fill: '#0f172a', selectable: false, evented: false,
      },
      {
        type: 'circle',
        left: 1200, top: -100, radius: 400,
        fill: 'rgba(56, 189, 248, 0.1)', selectable: false,
      },
      {
        type: 'textbox',
        text: 'JOHN DOE',
        left: 100, top: 150, width: 800,
        fontSize: 80, fontWeight: '800', fontFamily: 'Inter',
        fill: '#ffffff', charSpacing: 100,
      },
      {
        type: 'textbox',
        text: 'Software Engineer & Designer',
        left: 100, top: 250, width: 800,
        fontSize: 32, fontFamily: 'Inter',
        fill: '#38bdf8',
      },
      {
        type: 'rect',
        left: 100, top: 320, width: 60, height: 4,
        fill: '#e2e8f0',
      },
    ],
  },

  // ─── Movie Poster (poster) ───────────────────────────────────────────────
  {
    id: 'movie-poster',
    name: 'Movie Poster',
    category: 'poster',
    description: 'Cinematic minimal movie poster',
    thumbnail: '🎬',
    width: 2480,
    height: 3508,
    backgroundColor: '#000000',
    objects: [
      {
        type: 'rect',
        left: 0, top: 0, width: 2480, height: 3508,
        fill: '#000000', selectable: false, evented: false,
      },
      {
        type: 'textbox',
        text: 'A FILM BY DIRECTOR',
        left: 0, top: 400, width: 2480,
        fontSize: 60, fontWeight: '600', fontFamily: 'Inter',
        fill: '#ffffff', textAlign: 'center', charSpacing: 300,
      },
      {
        type: 'textbox',
        text: 'SILENCE',
        left: 0, top: 1200, width: 2480,
        fontSize: 400, fontWeight: '900', fontFamily: 'Georgia',
        fill: '#ffffff', textAlign: 'center', charSpacing: 50,
      },
      {
        type: 'textbox',
        text: 'COMING SOON TO THEATERS',
        left: 0, top: 3000, width: 2480,
        fontSize: 50, fontFamily: 'Inter',
        fill: '#94a3b8', textAlign: 'center', charSpacing: 400,
      },
    ],
  },

  // ─── Club Night Flyer (flyer) ────────────────────────────────────────────
  {
    id: 'club-flyer',
    name: 'Club Night Flyer',
    category: 'flyer',
    description: 'Neon synthwave party flyer',
    thumbnail: '🪩',
    width: 1080,
    height: 1350,
    backgroundColor: '#09090b',
    objects: [
      {
        type: 'rect',
        left: 0, top: 0, width: 1080, height: 1350,
        fill: '#09090b', selectable: false, evented: false,
      },
      {
        type: 'rect',
        left: 40, top: 40, width: 1000, height: 1270,
        fill: 'transparent', stroke: '#db2777', strokeWidth: 4, selectable: false,
      },
      {
        type: 'textbox',
        text: 'NEON',
        left: 0, top: 200, width: 1080,
        fontSize: 200, fontWeight: '900', fontFamily: 'Inter',
        fill: '#db2777', textAlign: 'center',
      },
      {
        type: 'textbox',
        text: 'NIGHTS',
        left: 0, top: 380, width: 1080,
        fontSize: 200, fontWeight: '900', fontFamily: 'Inter',
        fill: '#38bdf8', textAlign: 'center',
      },
      {
        type: 'textbox',
        text: 'FRIDAY 10PM / GUEST DJS',
        left: 0, top: 800, width: 1080,
        fontSize: 48, fontWeight: '700', fontFamily: 'Inter',
        fill: '#ffffff', textAlign: 'center', charSpacing: 100,
      },
      {
        type: 'textbox',
        text: '123 MAIN ST. DOWNTOWN',
        left: 0, top: 900, width: 1080,
        fontSize: 32, fontFamily: 'Inter',
        fill: '#a1a1aa', textAlign: 'center', charSpacing: 50,
      },
    ],
  },

  // ─── Award Certificate (certificate) ─────────────────────────────────────
  {
    id: 'award-certificate',
    name: 'Award Certificate',
    category: 'certificate',
    description: 'Modern employee of the month award',
    thumbnail: '🌟',
    width: 1080,
    height: 756,
    backgroundColor: '#ffffff',
    objects: [
      {
        type: 'rect',
        left: 0, top: 0, width: 1080, height: 756,
        fill: '#ffffff', selectable: false, evented: false,
      },
      {
        type: 'rect',
        left: 0, top: 0, width: 1080, height: 20,
        fill: '#2563eb', selectable: false,
      },
      {
        type: 'rect',
        left: 0, top: 736, width: 1080, height: 20,
        fill: '#2563eb', selectable: false,
      },
      {
        type: 'textbox',
        text: 'AWARD OF EXCELLENCE',
        left: 0, top: 100, width: 1080,
        fontSize: 48, fontWeight: '800', fontFamily: 'Inter',
        fill: '#1e293b', textAlign: 'center', charSpacing: 200,
      },
      {
        type: 'textbox',
        text: 'Presented to',
        left: 0, top: 220, width: 1080,
        fontSize: 24, fontFamily: 'Inter',
        fill: '#64748b', textAlign: 'center',
      },
      {
        type: 'textbox',
        text: 'Jane Doe',
        left: 0, top: 280, width: 1080,
        fontSize: 80, fontWeight: '700', fontFamily: 'Georgia',
        fill: '#2563eb', textAlign: 'center',
      },
      {
        type: 'textbox',
        text: 'For outstanding dedication and exceptional performance.',
        left: 0, top: 400, width: 1080,
        fontSize: 28, fontFamily: 'Inter',
        fill: '#475569', textAlign: 'center',
      },
    ],
  },

  // ─── Tech Resume (resume) ────────────────────────────────────────────────
  {
    id: 'tech-resume',
    name: 'Tech Resume',
    category: 'resume',
    description: 'Clean modern resume for developers',
    thumbnail: '👨‍💻',
    width: 816,
    height: 1056,
    backgroundColor: '#ffffff',
    objects: [
      {
        type: 'rect',
        left: 0, top: 0, width: 816, height: 1056,
        fill: '#ffffff', selectable: false, evented: false,
      },
      {
        type: 'rect',
        left: 40, top: 40, width: 736, height: 120,
        fill: '#f8fafc', rx: 8, ry: 8,
      },
      {
        type: 'textbox',
        text: 'David Smith',
        left: 60, top: 60, width: 400,
        fontSize: 40, fontWeight: '800', fontFamily: 'Inter',
        fill: '#0f172a',
      },
      {
        type: 'textbox',
        text: 'Full Stack Developer',
        left: 60, top: 110, width: 400,
        fontSize: 18, fontFamily: 'Inter',
        fill: '#3b82f6',
      },
      {
        type: 'textbox',
        text: 'david@example.com\ngithub.com/david\nSan Francisco, CA',
        left: 500, top: 60, width: 250,
        fontSize: 14, fontFamily: 'Inter',
        fill: '#64748b', textAlign: 'right', lineHeight: 1.5,
      },
      {
        type: 'textbox',
        text: 'EXPERIENCE',
        left: 60, top: 200, width: 700,
        fontSize: 16, fontWeight: '700', fontFamily: 'Inter',
        fill: '#0f172a', charSpacing: 100,
      },
      {
        type: 'rect',
        left: 60, top: 230, width: 700, height: 2,
        fill: '#e2e8f0',
      },
      {
        type: 'textbox',
        text: 'Senior Developer — Tech Corp',
        left: 60, top: 250, width: 700,
        fontSize: 16, fontWeight: '600', fontFamily: 'Inter',
        fill: '#1e293b',
      },
      {
        type: 'textbox',
        text: '2020 - Present',
        left: 60, top: 275, width: 700,
        fontSize: 14, fontFamily: 'Inter',
        fill: '#94a3b8',
      },
      {
        type: 'textbox',
        text: '• Built scalable web applications using React and Node.js.\n• Mentored junior developers and led code reviews.\n• Improved performance by 40% through code optimization.',
        left: 60, top: 310, width: 700,
        fontSize: 14, fontFamily: 'Inter',
        fill: '#475569', lineHeight: 1.6,
      },
    ],
  },

  // ─── Minimal Business Card (business-card) ───────────────────────────────
  {
    id: 'minimal-card',
    name: 'Minimal Card',
    category: 'business-card',
    description: 'Clean and elegant light business card',
    thumbnail: '💳',
    width: 1050,
    height: 600,
    backgroundColor: '#ffffff',
    objects: [
      {
        type: 'rect',
        left: 0, top: 0, width: 1050, height: 600,
        fill: '#ffffff', selectable: false, evented: false,
      },
      {
        type: 'rect',
        left: 0, top: 0, width: 1050, height: 600,
        fill: 'transparent', stroke: '#e2e8f0', strokeWidth: 2, selectable: false, evented: false,
      },
      {
        type: 'textbox',
        text: 'STUDIO.',
        left: 100, top: 250, width: 300,
        fontSize: 60, fontWeight: '900', fontFamily: 'Inter',
        fill: '#0f172a',
      },
      {
        type: 'textbox',
        text: 'Creative Agency',
        left: 100, top: 330, width: 300,
        fontSize: 20, fontFamily: 'Inter',
        fill: '#64748b', charSpacing: 100,
      },
      {
        type: 'rect',
        left: 450, top: 150, width: 1, height: 300,
        fill: '#cbd5e1',
      },
      {
        type: 'textbox',
        text: 'Sarah Jenkins',
        left: 550, top: 200, width: 400,
        fontSize: 40, fontWeight: '700', fontFamily: 'Inter',
        fill: '#0f172a',
      },
      {
        type: 'textbox',
        text: 'Art Director',
        left: 550, top: 255, width: 400,
        fontSize: 20, fontFamily: 'Inter',
        fill: '#3b82f6',
      },
      {
        type: 'textbox',
        text: '+1 (555) 123-4567\nsarah@studio.com\n123 Design St, NY',
        left: 550, top: 320, width: 400,
        fontSize: 18, fontFamily: 'Inter',
        fill: '#475569', lineHeight: 1.8,
      },
    ],
  },
]
